### PR TITLE
Renamed project and most scripts.

### PR DESCRIPTION
**Pull request by Rovanion**
The scripts according to the convention of action/component.

The project itself to Wordpress Mass Administration, or wp-mass-admin for short.

Also rewrote some parts of the readme. At least went through and made some style changes.

### CODE REVIEW

**Comment by Rovanion** [comment]
Rebased against master.

**Comment by Rovanion** [comment]
@hansfilipelo How does this look to youŋ

**Comment by hansfilipelo** [comment]
Patched and tested by me. Christian can you please look at my changes?

**Comment by Rovanion** [comment]
@hansfilipelo Looks good to me. I'll test it and merge it sunday if everything goes as planned.

**Comment by Rovanion** [comment]
Unable to get SSL working at home server. Will continue testing Tuesday.

**Comment by hansfilipelo** [comment]
Any error? 

Remember that the DNS-name you're using needs to point to your server.

**Comment by Rovanion** [comment]
No errors from the setup except those which I've added "fixes" for in this PR. The error is due to some fault in the SSH handshake and the weather was too good for me to spend the whole day debugging it :D

**Comment by hansfilipelo** [comment]
This is replaced by #22. Closing.

**Pull request closed without merging**
