### PR TITLE
SSL scan

### PR DESCRIPTION
**Pull request by Rovanion**
The scan suite now also includes testing from SSL labs. Only the grade is outputed as this is the only easily human readable output the script provides.

For a more detailed report the reader of the output from this script has to visit ssllabs.com. A feature request has been put up to the parent project, ssllabs-scan, for more detailed humanly readable output - but the request has yet to be fulfilled.

### CODE REVIEW

**Comment by hansfilipelo** [comment]
There's a git header in ssllabs-scan/ssllabs-scan.go

    <<<<<<< HEAD
    var USER_AGENT = "ssllabs-scan v1.1.0 ($Id: 29580ef3fe1363d3eae9fae0fc75c1434fb1f50c $)"
    =======
    var USER_AGENT = "ssllabs-scan v1.2.x (dev $Id: 29580ef3fe1363d3eae9fae0fc75c1434fb1f50c $)"
    >>>>>>> 77cb47172c2b1bd1b8646b430c4092c4811678ef

This causes issues with compile: 

    go build ssllabs-scan.go
    # command-line-arguments
    ./ssllabs-scan.go:53: syntax error: unexpected <<
    ./ssllabs-scan.go:55: syntax error: unexpected ==
    Makefile:2: recipe for target 'build' failed
    make: *** [build] Error 2
    Failed to compile ssllabs-scan!

I can't update the submodule with master from ssllabs-scan since a file has changed (ssllabs-scan.go has a header in it): 

    git submodule update --remote
    ssllabs-scan.go: needs merge
    error: you need to resolve your current index first
    Submodule path 'wpscan': checked out '36df5ee6e4f45fe0349663e8bdcc14ae604863ed'
    Unable to checkout '77cb47172c2b1bd1b8646b430c4092c4811678ef' in submodule path 'ssllabs-scan'

**Comment by Rovanion** [comment]
The issue stemmed from scan/scan:5 pulling in the master branch of ssllabs-scan while we were tracking the stable branch. This should no longer happen with the combination of remote branches being written in the .gitmodule file and the usage of another pull command in scan/scan.

**Comment by hansfilipelo** [comment]
Har fortfarande merge-headers i ssllabs-scan/ssllabs-scan.go

**Comment by hansfilipelo** [comment]
Klonade repot igen vilket löste det problemet.

**Pull request merged**
