### PR TITLE
Added support for Debian Jessie

### PR DESCRIPTION
**Pull request by hansfilipelo**
This adds support for Debian Jessie according to Issue #10

### CODE REVIEW

**Comment by Rovanion** [comment]
I'm getting this wierd thing on wp.cyd.liu.se where ```fastcgi_param   SCRIPT_FILENAME /;``` still ends up in the nginx-conf even though I'm on the jessie branch and ```install/nginx.bash``` reads ```fastcgi_param   SCRIPT_FILENAME $document_root/$fastcgi_\
script_name;```.

**Comment by hansfilipelo** [comment]
Hmm... I think the shell reads anything in:

<pre> $document_root/$fastcgi_\ script_name;</pre>

... with dollar sign as a variable. I guess this problem can be fixed by stopping the output to file before that line and writing that line explicitly (with single quotes -> ') to the config file.

**Comment by Rovanion** [comment]
It should also be possible to escape the dollar signs with backslash.

**Comment by Rovanion** [comment]
I'm quite sure that I tested this on wp about a month back and it worked just fine. So I'm merging this.

**Pull request merged**
